ARG PYTHON_VERSION=3.13
ARG APP_HOME=/home/app

FROM python:${PYTHON_VERSION}-alpine
ARG PYTHON_VERSION
ARG APP_HOME
LABEL org.opencontainers.image.authors="Jorge Mentxaka <jordims2000@gmail.com>"

ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PYTHON_DOWNLOADS=never \
    UV_PYTHON=python${PYTHON_VERSION} \
    UV_PROJECT_ENVIRONMENT=${APP_HOME}/venv
ENV PATH="${APP_HOME}/venv/bin:$PATH"

RUN addgroup -S app && adduser -S app -G app
WORKDIR ${APP_HOME}

ONBUILD COPY ./pyproject.toml .
ONBUILD COPY ./uv.lock .
ONBUILD RUN --mount=from=ghcr.io/astral-sh/uv,source=/uv,target=/bin/uv uv sync --locked --all-groups --no-dev --no-install-project --no-editable

ONBUILD USER app
